{
  "hash": "9de7bdf4e9dfcdc4c505f693edfdcd69",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"DNN vs ML 모델 비교 인사이트\"\nsubtitle: \"선형·트리·딥러닝 모델의 공정 비교 분석 및 핵심 발견\"\nformat:\n  html:\n    code-fold: true\n    toc: true\n---\n\n\n\n\n본 페이지는 논문의 핵심 리뷰 결과인 **DNN(딥러닝) vs ML(선형/트리) 모델 비교** 인사이트를 시각화합니다.\n\n::: {.callout-note}\n## 핵심 발견\n- **단기(1~22d)**: 정규화 선형 모델(Ridge/ElasticNet)이 최강\n- **중기(60~90d)**: BiLSTM-A(3 피처)가 37피처 선형 모델을 능가\n- **장기(180~252d)**: Random Forest 트리 앙상블이 가장 안정적\n- **복잡도 ≠ 성능**: Transformer(~85K params)는 과적합, Ridge(~38 params)가 우수\n:::\n\n---\n\n## 1. 지평별 챔피언 모델 히트맵\n\n8개 예측 지평에 걸쳐 5개 주요 모델의 풀링 R^2를 비교합니다. 선형→DL→트리로 우위가 교차하는 패턴이 핵심 발견입니다.\n\n::: {#cell-heatmap-champion .cell fig-height='6' fig-width='14' execution_count=1}\n\n::: {.cell-output .cell-output-display}\n![](dnn_vs_ml_insights_files/figure-html/heatmap-champion-output-1.png){#heatmap-champion width=1311 height=565}\n:::\n:::\n\n\n::: {.callout-tip}\n## 지평별 최적 모델이 다른 이유\n- **단기**: HAR 자기상관이 강해 다수 피처 선형 결합이 유효\n- **중기**: Range 피처의 비선형 시계열 패턴을 LSTM이 포착\n- **장기**: 노이즈가 지배적 → 트리 앙상블의 강건성이 유리\n:::\n\n---\n\n## 2. 22거래일 공정 비교 (15개 모델)\n\n동일 데이터·동일 37피처·동일 검증 절차 하에서 15개 모델을 비교한 결과입니다.\n\n::: {#cell-fair-comparison-22d .cell fig-height='8' fig-width='14' execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](dnn_vs_ml_insights_files/figure-html/fair-comparison-22d-output-1.png){#fair-comparison-22d width=1332 height=758}\n:::\n:::\n\n\n### 22d 공정 비교 요약 (표 9 발췌)\n\n| Model | Type | #Feat | Pooled R² | Median R² | RMSE |\n|:---|:---|:---:|:---:|:---:|:---:|\n| **ElasticNet-59** | Linear | 59 | **0.807** | -- | 0.459 |\n| **WEns** | Ensemble | 37 | **0.803** | **0.215** | 0.468 |\n| BiLSTM-A | DL | 3 | 0.780 | 0.235 | 0.477 |\n| RF | Tree | 37 | 0.759 | 0.142 | 0.513 |\n| HAR-3 | Linear | 3 | 0.761 | 0.171 | 0.542 |\n| MLP | NN | 37 | 0.618 | -0.327 | 0.646 |\n| Transformer | DL | 37 | 0.534 | -- | -- |\n\n---\n\n## 3. 모델 복잡도 vs 성능\n\n파라미터 수가 많다고 성능이 좋아지지 않습니다. 변동성 예측의 고잡음 환경에서는 적절한 규제가 핵심입니다.\n\n::: {#cell-complexity-vs-performance .cell fig-height='7' fig-width='12' execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![](dnn_vs_ml_insights_files/figure-html/complexity-vs-performance-output-1.png){#complexity-vs-performance width=1137 height=660}\n:::\n:::\n\n\n::: {.callout-important}\n## 복잡도 패러독스\n- **Ridge (~38 params)**: R² = 0.762 → 최소 파라미터로 준수한 성능\n- **Transformer (~85K params)**: R² = 0.534 → 과적합으로 **최악의 성능**\n- **WEns (~1K params)**: R² = 0.803 → 적절한 복잡도에서 **최고 성능**\n\n> 변동성 예측 환경 특유의 고잡음 환경에서는 수만 개의 파라미터를 가진 거대 딥러닝보다 정교하게 설계된 소규모 모델이 안정적인 성능을 달성합니다.\n:::\n\n---\n\n## 4. 딥러닝 피처 통제 실험\n\nBiLSTM-A에 37개 전체 피처를 적용하면 차원의 저주로 성능이 급락합니다.\n\n::: {#cell-dl-feature-control .cell fig-height='6' fig-width='14' execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![](dnn_vs_ml_insights_files/figure-html/dl-feature-control-output-1.png){#dl-feature-control width=1335 height=566}\n:::\n:::\n\n\n::: {.callout-warning}\n## 차원의 저주 (Curse of Dimensionality)\nBiLSTM-A에 37개 전체 피처를 적용한 결과:\n- 풀링 R²가 **0.780 → 0.538**로 급락 (-0.242)\n- 대다수 개별 자산에서 **음수 R²** 기록 (SPY -0.18, QQQ -0.81)\n- 딥러닝 예측이 단순 역사적 평균보다 못한 결과\n\n이는 3개 핵심 range 피처 선택이 \"불공정한 모델 축소\"가 아니라 **과적합 통제를 위한 최적의 피처 설계**였음을 입증합니다.\n:::\n\n---\n\n## 5. 핵심 인사이트 종합\n\n::: {#cell-insight-summary .cell fig-height='7' fig-width='14' execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![](dnn_vs_ml_insights_files/figure-html/insight-summary-output-1.png){#insight-summary width=1333 height=660}\n:::\n:::\n\n\n---\n\n## 리뷰 결론\n\n::: {.callout-important}\n## 5가지 핵심 발견\n\n1. **\"복잡도 ≠ 성능\" 원칙 확립**: 변동성 예측처럼 잡음이 높은 금융 시계열에서는 Transformer(85K params) 같은 거대 모델보다 Ridge(38 params) + 적절한 규제가 훨씬 효과적이다.\n\n2. **지평별 최적 모델 교차 현상**: 하나의 모델이 모든 지평에서 최적이 아니다. 단기는 선형(WEns), 중기는 DL(BiLSTM-A), 장기는 트리(RF)로 지평에 따라 최적 구조가 달라진다.\n\n3. **피처 설계가 모델 구조보다 중요**: BiLSTM-A가 3개 range 피처만으로 37피처 선형 모델과 경쟁한 반면, 37피처를 넣으면 R²가 0.780→0.538로 급락. 피처 선택이 모델 복잡도보다 결정적이다.\n\n4. **VIX 레짐별 차별적 개선**: WEns의 HAR-3 대비 개선 폭은 High VIX(상위 10%) 구간에서 +0.163으로 가장 크다. 위기 시 IV Surface와 HF Proxy 피처의 추가 정보가 핵심이다.\n\n5. **앙상블의 가치**: 선형(Ridge 70%) + 트리(XGBoost 30%) 결합이 개별 모델 대비 일관된 개선을 제공하며 R²=0.80 벽을 돌파했다.\n:::\n\n---\n\n## 관련 자료\n\n- [모델 아키텍처 비교](/experiments/phase13_model_comparison.html) - Multi-Horizon 상세 비교\n- [V71 Ridge 분석](/experiments/22day_prediction.html) - 단기 챔피언 상세\n- [V50 LSTM 분석](/experiments/1day_prediction.html) - 중기 챔피언 상세\n- [피처 분석](/experiments/feature_analysis.html) - 피처 중요도 상세\n- [V71 강건성 검증](/experiments/champion_robustness.html) - 6종 강건성 테스트\n\n",
    "supporting": [
      "dnn_vs_ml_insights_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}