{
  "hash": "4f577a5a5550f8a950a0c99c6e0a4e1a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"챔피언 모델 강건성 검증\"\nsubtitle: \"V50 Tuned (중기) 및 V71 (단기) 모델의 신뢰성 분석\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n---\n\n\n\n\n# 개요\n\n본 페이지는 중기 예측 챔피언(**V50 Tuned**)과 단기 예측 챔피언(**V71**)의 강건성(Robustness) 검증 결과입니다.\n\n모든 성능 지표는 **11개 자산 풀링 기준**입니다: Equity(SPY, QQQ, IWM, EFA, EEM), Bond(TLT, IEF, AGG), Commodity(GLD, SLV, USO)\n\n---\n\n# V50 Original (overlapping 22d 기준) 검증\n\n## 공정 비교 실험 (v51b)\n\nV50의 성능을 정확히 평가하기 위해 동일한 실험 설정(rolling=22, target=t+22)에서 공정 비교를 수행했습니다.\n\n| 지표 | 값 | 해석 |\n|:---|:---|:---|\n| **IS R²** | 0.848 | 훈련 데이터 성능 |\n| **OOS R²** | **0.651** | 미래 데이터 일반화 |\n| **IS-OOS Gap** | 0.315 | 과적합 정도 |\n\n::: {.callout-info}\n## 수정 이력\n- v66 결과(R². 0.99): 데이터 누출 확인 → 삭제\n- v51 결과(R² 0.820): 실험 설정 불일치 → 수정됨\n- **v51b 결과(R² 0.651)**: 공정 비교 → 최종 확정\n:::\n\n## Extreme Market 테스트 (v59)\n\n| 국면 | 설명 | R² Score |\n|:---|:---|:---|\n| **위기 (08-09)** | 금융위기 | **0.772** |\n| **정상 (12-19)** | 저변동성 | 0.517 |\n| **COVID (2020)** | 팬데믹 | **0.548** |\n| **인플레 (2022)** | 고금리 | 0.306 |\n\n---\n\n# V71 (22일 예측) 검증\n\nV71 모델은 37개 피처의 Ridge + XGBoost 가중 앙상블로 전방 RV 기준 22d R²=0.803을 달성하였으며, **6종 강건성 테스트를 모두 통과**했습니다.\n\n## 강건성 시각화\n\n::: {#7889bc1e .cell fig-height='10' fig-width='12' execution_count=1}\n\n::: {.cell-output .cell-output-display}\n![](champion_robustness_files/figure-html/cell-2-output-1.png){width=1139 height=950}\n:::\n:::\n\n\n## 검증 결과 요약\n\n| 검증 방법 | 결과 | 판정 |\n|:---------|:-----|:-----|\n| 다중 Split 안정성 | R² = 0.793 ± 0.010 (5개 split) | **PASS** |\n| Alpha 민감도 | R² = 0.788~0.802 (0.001~5000) | **PASS** |\n| 5-Fold 시계열 CV | R² = 0.765 ± 0.046 | **PASS** |\n| 데이터 누출 검증 | 셔플 R² = -0.002 | **PASS** |\n| Permutation Importance | Rogers-Satchell 1위 (0.731) | **PASS** |\n| DM Test (Newey-West) | 모든 p < 0.001 | **PASS** |\n\n## 자산군별 성능 (V36 vs V71)\n\n::: {#6c07d0b4 .cell fig-height='5' fig-width='12' execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](champion_robustness_files/figure-html/cell-3-output-1.png){width=1142 height=471}\n:::\n:::\n\n\n## VIX 국면별 안정성\n\n::: {#0e6bf063 .cell fig-height='5' fig-width='10' execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![](champion_robustness_files/figure-html/cell-4-output-1.png){width=950 height=471}\n:::\n:::\n\n\n::: {.callout-important}\n## High VIX 국면 우월성\n가장 예측이 어려운 **High VIX (상위 10%)** 구간에서 V71은 **R² 0.765**를 기록하여 V36(0.602) 대비 **+16.3%p** 개선.\n:::\n\n---\n\n# 종합 결론\n\n| 항목 | V50 Tuned (중기) | V71 (단기) |\n|:---|:---|:---|\n| **22d R²** (전방 RV) | 0.780 | **0.803** |\n| **60d R²** (전방 RV) | **0.796** | 0.774 |\n| **CV/Multi-seed** | - | R² = 0.793 ± 0.010 |\n| **DM Test** | p < 0.001 | p < 0.001 (모든 비교) |\n| **위기 국면** | - | R² 0.765 (High VIX) |\n| **피처 수** | 3 (Range) | 37 |\n| **모델 유형** | Bi-LSTM + Attention | Ridge |\n\n## 관련 자료\n- [V71 강건성 데이터](/paper/csv/v71_robustness_results.json)\n- [V50 공정 비교 결과](../src/experiments/verification/v51b_results.json)\n- [V71 실험 결과](/paper/csv/v71_results.json)\n\n",
    "supporting": [
      "champion_robustness_files"
    ],
    "filters": [],
    "includes": {}
  }
}