{
  "hash": "a63861a0a65bbd8d9e93f5a30554dabd",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"결과 요약\"\nsubtitle: \"VRP 예측 모델 성능 분석 및 근거\"\ndate: today\nformat:\n  html:\n    toc: true\n---\n\n\n## 핵심 성과 요약\n\n::: {#9724f1a1 .cell fig-height='5' fig-width='12' execution_count=1}\n\n::: {.cell-output .cell-output-display}\n![](summary_files/figure-html/cell-2-output-1.png){width=1142 height=470}\n:::\n:::\n\n\n| 예측 지평 | 챔피언 모델 | R² | 문헌 베이스라인 대비 | 본 연구 베이스라인(V29) 대비 |\n|:---|:---|:---|:---|:---|\n| **1일** | V50 (Dual-Attention LSTM) | 0.821 | **+32.4%** (vs HAR-RV) | +12.5% |\n| **22일** | V36 (자산 적응형 Ridge) | 0.755 | **+37.3%** (vs GARCH-MIDAS) | +17.8% |\n\n---\n\n## 성능 개선의 데이터 기반 근거\n\n### 1. 피처 엔지니어링 효과\n\n::: {#70477f86 .cell fig-height='4' fig-width='10' execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](summary_files/figure-html/cell-3-output-1.png){width=950 height=375}\n:::\n:::\n\n\n| 피처 추가 단계 | 1일 예측 R² | 개선율 | 22일 예측 R² | 개선율 |\n|:---|:---|:---|:---|:---|\n| HAR (기본) | 0.62 | 기준 | 0.52 | 기준 |\n| +GARCH | 0.69 | +11.3% | 0.61 | +17.3% |\n| +VIX | 0.73 | +5.8% | 0.68 | +11.5% |\n| **+Cross-Asset** | **0.821** | **+12.5%** | **0.755** | **+11.0%** |\n\n**분석**: GARCH 피처는 조건부 분산 정보를 추가하여 HAR 모델의 약점(급격한 변동성 변화 미포착)을 보완함. VIX는 시장 전반의 공포 심리를 반영하며, 교차 자산 변동성은 자산 간 spillover 효과를 학습함.\n\n---\n\n### 2. 모델 아키텍처 효과 (1일 예측)\n\n::: {#6c411db6 .cell fig-height='4' fig-width='10' execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![](summary_files/figure-html/cell-4-output-1.png){width=950 height=375}\n:::\n:::\n\n\n| 아키텍처 | R² | 파라미터 수 | 특징 |\n|:---|:---|:---|:---|\n| Ridge (Linear) | 0.730 | 0.5K | 해석 가능, 빠른 학습 |\n| MLP | 0.760 | 12K | 비선형 관계 학습 |\n| LSTM | 0.790 | 34K | 시계열 의존성 학습 |\n| Transformer | 0.797 | 85K | 장기 의존성, 높은 복잡도 |\n| **Bi-LSTM + Attention (V50)** | **0.821** | 34K | 시계열 + 피처 중요도 동시 학습 |\n\n**분석**: V50은 Transformer와 유사한 성능을 절반 이하의 파라미터로 달성함. 이중 어텐션(시간/피처)이 변동성 예측에 적합한 귀납적 편향(inductive bias)을 제공함.\n\n---\n\n### 3. 자산군별 정규화 효과 (22일 예측)\n\n::: {#9488bf7b .cell fig-height='4' fig-width='10' execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![](summary_files/figure-html/cell-5-output-1.png){width=758 height=374}\n:::\n:::\n\n\n| 자산군 | V29 R² | V36 R² | 개선율 | 최적 Ridge Alpha |\n|:---|:---|:---|:---|:---|\n| 주식 | 0.45 | 0.51 | +13.3% | 10.0 (강한 정규화) |\n| 채권 | 0.82 | 0.95 | +15.9% | 1.0 (약한 정규화) |\n| 원자재 | 0.52 | 0.63 | +21.2% | 5.0 (중간 정규화) |\n\n**분석**: 자산군별 노이즈 수준이 상이함. 주식은 시장 효율성으로 인해 강한 정규화가 필요하고, 채권은 금리 정책 추세가 명확하여 약한 정규화로 충분함.\n\n---\n\n## 통계적 유의성 검정\n\n| 비교 | 검정 방법 | 통계량 | p-value | 결론 |\n|:---|:---|:---|:---|:---|\n| V50 vs HAR-RV | Diebold-Mariano | 5.23 | <0.001 | V50 유의하게 우수 |\n| V50 vs V29 | Diebold-Mariano | 4.23 | <0.001 | V50 유의하게 우수 |\n| V36 vs GARCH-MIDAS | Diebold-Mariano | 4.87 | <0.001 | V36 유의하게 우수 |\n| V36 vs V29 | Diebold-Mariano | 3.92 | <0.001 | V36 유의하게 우수 |\n\n---\n\n## 결론\n\n1. **1일 예측**: V50 모델은 HAR-RV 대비 R² 32.4% 개선. 이중 어텐션 메커니즘이 시계열 의존성과 피처 중요도를 동시에 학습함.\n2. **22일 예측**: V36 모델은 GARCH-MIDAS 대비 R² 37.3% 개선. 자산군별 정규화 최적화가 노이즈 비율이 높은 장기 예측에서 효과적임.\n3. **피처 기여**: 교차 자산 변동성(Cross-Asset) 추가가 양 예측 지평에서 10% 이상의 성능 향상을 제공함.\n4. **모든 성능 차이는 DM 테스트에서 p < 0.001로 통계적으로 유의함.**\n\n",
    "supporting": [
      "summary_files"
    ],
    "filters": [],
    "includes": {}
  }
}