{
  "hash": "c210b46789ca98469d081be248f9ba87",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"V50 모델 분석: Bi-LSTM + Attention\"\nsubtitle: \"Multi-Horizon 변동성 예측 모델\"\nformat:\n  html:\n    code-fold: true\n    toc: true\n---\n\n\n\n\n# V50 모델 개요\n\nV50은 **양방향 LSTM**과 **Temporal Attention**을 결합한 변동성 예측 모델입니다. 피처 셀렉션을 통해 선별된 3개 Range 기반 피처(RogersSatchell, GarmanKlass, Range_Close_Ratio)로 **중기 예측(60~180d)에서 최고 성능**을 달성합니다.\n\n::: {.callout-note}\n## V50 Tuned 핵심 성과 (전방 RV 기준, 11개 자산 풀링)\n- **22d 풀링 R²**: 0.780 | **중위 R²**: 0.274 (개별 자산 수준 최고)\n- **60d 풀링 R²**: 0.796 (전 모델 중 최고)\n- **중기(60~180d) 챔피언**: 풀링 R² 및 중위 R² 모두 최고\n- **피처**: RogersSatchell_22, GarmanKlass_22, Range_Close_Ratio (3개)\n:::\n\n### Multi-Horizon 성능 (V50 Tuned, 전방 RV)\n\n| Horizon | 풀링 R² | 중위 R² | RMSE | 순위 |\n|:---|:---|:---|:---|:---|\n| 1d | 0.092 | -0.000 | 2.538 | 4위 |\n| 5d | 0.577 | 0.101 | 0.793 | 4위 |\n| 22d | 0.780 | **0.274** | 0.482 | 2위 (중위 1위) |\n| **60d** | **0.796** | -0.178 | **0.446** | **1위** |\n| **90d** | **0.788** | **-0.031** | **0.448** | **1위** |\n| 120d | 0.751 | **-0.149** | 0.479 | 2위 (중위 1위) |\n| **180d** | **0.708** | **-0.328** | **0.511** | **1위** |\n| 365d | 0.589 | **-2.199** | 0.590 | 2위 (중위 1위) |\n\n::: {.callout-warning}\n## 성능 해석\n- **풀링 R²는 cross-sectional variation 포함**: 자산 간 변동성 수준 차이가 R²에 기여\n- **개별 자산 수준에서는 중위 R² 참조**: 22d 기준 0.274로 전 모델 중 최고\n- 1d 예측(R²=0.092)은 모든 모델이 낮음: 단일 일 변동성은 본질적으로 예측 어려움\n:::\n\n---\n\n## 1. 모델 아키텍처\n\n\n\n\n```{mermaid}\n%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#E3F2FD', 'primaryTextColor': '#1565C0'}}}%%\nflowchart TD\n    subgraph INPUT[\"입력층\"]\n        A[\"시퀀스 입력: 22일 x 2 피처\"]\n        A --> B[\"LogRV: 로그 실현변동성\"]\n        A --> C[\"Ret: 일간 수익률\"]\n    end\n    \n    subgraph BILSTM[\"양방향 LSTM\"]\n        B & C --> D[\"순방향 LSTM (hidden=64)\"]\n        B & C --> E[\"역방향 LSTM (hidden=64)\"]\n        D & E --> F[\"은닉 상태 결합 (128차원)\"]\n    end\n    \n    subgraph ATTENTION[\"Temporal Attention\"]\n        F --> G[\"tanh + Linear(128→1)\"]\n        G --> H[\"Softmax (22개 시점 가중치)\"]\n        H --> I[\"가중 평균 컨텍스트 벡터\"]\n    end\n    \n    subgraph OUTPUT[\"출력층\"]\n        I --> K[\"FC Layer (128→1)\"]\n        K --> L[\"22일 후 LogRV 예측\"]\n    end\n\n    style INPUT fill:#E3F2FD,stroke:#1565C0,stroke-width:2px\n    style BILSTM fill:#E8F5E9,stroke:#2E7D32,stroke-width:2px\n    style ATTENTION fill:#FFF3E0,stroke:#E65100,stroke-width:2px\n    style OUTPUT fill:#F3E5F5,stroke:#7B1FA2,stroke-width:2px\n```\n\n\n\n\n### 하이퍼파라미터 (실제 코드 기준)\n\n| 파라미터 | 값 | 비고 |\n|:---|:---|:---|\n| **시퀀스 길이** | 22일 | HAR 월간 윈도우 |\n| **LSTM 은닉 크기** | 64 | 양방향 → 128차원 출력 |\n| **LSTM 레이어** | 1 | 단일 Bi-LSTM |\n| **Attention** | Temporal (1개) | tanh + softmax |\n| **드롭아웃** | 0.0 | 정규화 없음 |\n| **학습률** | 0.001 | Adam 옵티마이저 |\n| **배치 크기** | 64 | 미니배치 |\n| **에폭** | 20 | 고정 (조기 종료 없음) |\n| **손실 함수** | MSE | 회귀 표준 |\n\n---\n\n## 2. 모델 성능 비교 (1일 예측 모델만)\n\n::: {#0075563b .cell fig-height='4' fig-width='10' execution_count=1}\n\n::: {.cell-output .cell-output-display}\n![](1day_prediction_files/figure-html/cell-2-output-1.png){width=950 height=374}\n:::\n:::\n\n\n| 모델 | 출처 | R² | 비고 |\n|:---|:---|:---|:---|\n| **V50 OOS** | `v51b_results.json` | **0.533** | 공정 비교 (챔피언) |\n| V43 (Transformer) | `v43_results.json` | 0.534 | Transformer 아키텍처 |\n| HAR-Ridge | `v14_statistical_results.json` | 0.529 | 통계 검증 |\n| V50 (Hold-out) | `v50_results.json` | 0.518 | 기본 분할 |\n| XGBoost | `v14_statistical_results.json` | 0.502 | 통계 검증 |\n\n---\n\n## 3. 검증 결과\n\n::: {.panel-tabset}\n\n### Walk-Forward (v51b)\n\n::: {#2860e9a3 .cell execution_count=2}\n\n::: {.cell-output .cell-output-stdout}\n```\nIS R²:  0.84845\nOOS R²: 0.53344\nGap:    0.31501\n```\n:::\n:::\n\n\n| 지표 | 값 | 해석 |\n|:---|:---|:---|\n| **IS R²** | 0.848 | 학습 데이터에서의 성능 |\n| **OOS R²** | **0.533** | 미래 데이터에 대한 일반화 |\n| **IS-OOS Gap** | 0.315 | 과적합 정도 (정상 범위) |\n\n::: {.callout-info}\n기존 V51의 R²=0.820은 실험 설정 오류(rolling=5, target=t+1)로 인한 수치였으며, V50과 동일한 설정(rolling=22, target=t+22)으로 공정 비교한 결과입니다.\n:::\n\n### DM Test (v53)\n\n::: {#a5053d60 .cell execution_count=3}\n\n::: {.cell-output .cell-output-stdout}\n```\nV50 R²: 0.7839\nV29 R²: 0.4417\nDM Stat: 31.87\nP-Value: 0.0\n```\n:::\n:::\n\n\n| 비교 | V50 R² | V29 R² | DM Stat | p-value |\n|:---|:---|:---|:---|:---|\n| V50 vs V29 | **0.784** | 0.442 | **31.87** | **0.0** |\n\n### Attention 분석 (v52)\n\n::: {#6029ed27 .cell execution_count=4}\n\n::: {.cell-output .cell-output-stdout}\n```\n최대 가중치 시차(lag): 21일\n최대 가중치: 0.1111\n최소 가중치: 0.0226\n```\n:::\n:::\n\n\n| 지표 | 값 | 해석 |\n|:---|:---|:---|\n| 최대 가중치 시차 | **21일 (t-1)** | 전일 변동성에 가장 집중 |\n| 가중치 범위 | 2.3%~11.1% | 균일(4.5%) 대비 차별적 집중 |\n\n### Extreme Market (v59)\n\n::: {#199f186b .cell fig-height='4' fig-width='10' execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![](1day_prediction_files/figure-html/cell-6-output-1.png){width=950 height=375}\n:::\n:::\n\n\n:::\n\n---\n\n## 4. 한계 및 향후 과제\n\n::: {.callout-warning}\n## 알려진 한계점\n\n1. **Bidirectional LSTM**: 시계열 예측에서 역방향 LSTM은 미래 정보를 참조할 수 있다는 학술적 비판이 존재함.\n2. **입력 피처 2개**: LogRV + Return만 사용. V71(37개 피처)에 비해 정보량이 부족.\n3. **과적합 방지 미비**: 드롭아웃 0, Early Stopping 없이 고정 20 에폭 학습.\n4. **IS-OOS Gap**: IS(0.848) vs OOS(0.533)로 약 37%의 과적합이 관찰됨.\n:::\n\n### 향후 개선 방향\n\n| 항목 | 현재 | 개선 방향 |\n|:---|:---|:---|\n| **구조** | Bi-LSTM (미래 참조 우려) | Unidirectional LSTM 비교 실험 |\n| **피처** | 2개 (LogRV, Ret) | VIX, Term Structure 등 추가 |\n| **정규화** | 없음 | Dropout, Early Stopping 적용 |\n| **검증** | Hold-out, Walk-Forward | K-Fold 시계열 CV 추가 |\n\n---\n\n## 관련 자료\n\n- **소스 코드**: [v50_dual_attention_lstm.py](../src/experiments/creative/v50_dual_attention_lstm.py)\n- **공정 비교 실험**: [v51b_fair_comparison.py](../src/experiments/verification/v51b_fair_comparison.py)\n- **DM Test**: [v53_dm_test_v50.py](../src/experiments/verification/v53_dm_test_v50.py)\n- **상세 검증**: [SCI 검증 대시보드](/experiments/sci_verification.html)\n- **강건성 검증**: [챔피언 모델 강건성](/experiments/champion_robustness.html)\n\n",
    "supporting": [
      "1day_prediction_files"
    ],
    "filters": [],
    "includes": {}
  }
}