{
  "hash": "42aaf14c3a0080825d459fae2fbed82d",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"22일 예측 모델\"\nsubtitle: \"V71 (Enhanced Asset-Adaptive Ridge) 챔피언 모델\"\nformat:\n  html:\n    code-fold: true\n    toc: true\n---\n\n\n\n\n# 22일 예측 챔피언: V71 (Enhanced Asset-Adaptive Ridge)\n\n장기(22일) 변동성 예측에서 **V71 모델**은 OHLCV 기반 고빈도 프록시(HF Proxy), 옵션 내재변동성(IV Surface), 대안 데이터(Alternative Data)를 통합하여 37개 피처를 활용합니다. 자산 클래스별 최적화된 Ridge 회귀와 XGBoost의 가중 앙상블로 최고 성능을 달성했습니다.\n\n::: {.callout-note}\n## 핵심 성과 (11개 자산 풀링 기준)\n- **22d 풀링 R² = 0.803** (Weighted Ensemble, V36 대비 +5.5%)\n- Ridge 단독 R² = 0.798, XGBoost 단독 R² = 0.773\n- **대상 자산**: Equity(SPY, QQQ, IWM, EFA, EEM), Bond(TLT, IEF, AGG), Commodity(GLD, SLV, USO)\n- **DM test p<0.001** (모든 벤치마크 대비 통계적 유의)\n- **High VIX 국면 R² = 0.765** (V36: 0.602, +0.163 개선)\n:::\n\n---\n\n## 모델 성능 비교\n\n::: {#2f7ae905 .cell fig-height='6' fig-width='14' execution_count=1}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-2-output-1.png){width=1334 height=562}\n:::\n:::\n\n\n| 분류 | 모델 | R² | RMSE | MAE | QLIKE | 설명 |\n|:---|:---|:---|:---|:---|:---|:---|\n| 본 연구 | V29 (HAR+GARCH) | 0.641 | - | - | - | 기초 HAR 모델 |\n| 본 연구 | V36 (Adaptive Ridge) | 0.755 | - | - | - | 자산별 적응형 Ridge |\n| 본 연구 | V43 (Transformer) | 0.534 | - | - | - | DL 실패 사례 |\n| 본 연구 | **V50 (LSTM-Attn 3feat)** | 0.780 | 0.482 | 0.387 | 0.119 | Bi-LSTM+Attention, 중기 챔피언 |\n| 본 연구 | V68 (Enhanced) | 0.777 | - | - | - | V36 개선 시도 |\n| 본 연구 | **V71 Ridge (37feat)** | 0.798 | 0.469 | 0.377 | 0.134 | 자산별 alpha 튜닝 |\n| 본 연구 | **V71 Ensemble** | **0.803** | **0.468** | **0.377** | **0.133** | Ridge + XGBoost 가중 앙상블 |\n| 본 연구 | V73 (59feat) | 0.802 | - | - | - | 확장 피처 (Ridge) |\n| 본 연구 | **V74 (ElasticNet 59feat)** | **0.807** | - | - | - | **22d 최종 챔피언** |\n| 벤치마크 | HAR-RV (Corsi, 2009) | 0.761 | 0.508 | 0.402 | 0.153 | 3개 HAR 피처 |\n| 벤치마크 | HAR-CJ (Andersen+, 2007) | 0.752 | 0.517 | 0.410 | 0.158 | Jump 분해 |\n| 벤치마크 | LASSO-HAR (Audrino+, 2016) | 0.790 | 0.476 | 0.377 | 0.136 | 37개 피처 L1 |\n| 벤치마크 | RF (Christensen+, 2023) | 0.770 | 0.498 | 0.394 | 0.146 | 37개 피처 RF |\n\n### Diebold-Mariano 검정 (Newey-West HAC, h=22)\n\n| 비교 | DM 통계량 | p-value | 유의수준 |\n|:---|:---|:---|:---|\n| V71 Ensemble vs V36 | -8.802 | <0.001 | *** |\n| V71 Ensemble vs V68 | -8.756 | <0.001 | *** |\n| V71 Ridge vs V36 | -7.481 | <0.001 | *** |\n| V71 Ridge vs V68 | -7.593 | <0.001 | *** |\n\n---\n\n## V71 모델 구조 상세\n\n### 전체 아키텍처 개요\n\n::: {#6898bddf .cell fig-height='7' fig-width='10' execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-3-output-1.png){width=950 height=662}\n:::\n:::\n\n\n---\n\n### 37개 피처 그룹 상세 분류\n\n::: {#14ca28c6 .cell fig-height='7' fig-width='14' execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-4-output-1.png){width=1329 height=664}\n:::\n:::\n\n\n---\n\n### 피처 상세 목록\n\n::: {.panel-tabset}\n\n#### Base Features (14개)\n\n| # | 변수명 | 설명 | 계산 방식 |\n|:--:|:---|:---|:---|\n| 1 | `LogRV_lag1` | 전일 Log-RV | $\\log(\\text{RV}_{t-1})$ |\n| 2 | `LogRV_lag5` | 5일 전 Log-RV | $\\log(\\text{RV}_{t-5})$ |\n| 3 | `LogRV_lag10` | 10일 전 Log-RV | $\\log(\\text{RV}_{t-10})$ |\n| 4 | `LogRV_lag22` | 22일 전 Log-RV (월간) | $\\log(\\text{RV}_{t-22})$ |\n| 5 | `Garch_Daily` | 일별 GARCH(1,1) 변동성 | `arch` 패키지 rolling fit |\n| 6 | `Garch_Weekly` | 주별 GARCH 변동성 | 주간 수익률 기반 GARCH → ffill |\n| 7 | `LogRV_Std5` | 5일 Vol-of-Vol | $\\text{std}(\\log \\text{RV}, 5\\text{d})$ |\n| 8 | `LogRV_Std22` | 22일 Vol-of-Vol | $\\text{std}(\\log \\text{RV}, 22\\text{d})$ |\n| 9 | `RV_Mom5` | 5일 변동성 모멘텀 | $\\log \\text{RV}_t - \\log \\text{RV}_{t-5}$ |\n| 10 | `RV_Mom22` | 22일 변동성 모멘텀 | $\\log \\text{RV}_t - \\log \\text{RV}_{t-22}$ |\n| 11 | `SPY_LogRV` | SPY Log-RV (시장 참조) | SPY 22일 RV의 로그 |\n| 12 | `Ret_lag1` | 전일 로그 수익률 | $\\log(P_t / P_{t-1})$ |\n| 13 | `Ret_abs_lag1` | 전일 절대 수익률 | $|\\log(P_t / P_{t-1})|$ |\n| 14 | `Corr_SPY` | SPY 상관계수 | 22일 rolling 상관 |\n\n#### HF Proxy (7개)\n\n| # | 변수명 | 설명 | 계산 방식 |\n|:--:|:---|:---|:---|\n| 1 | `Parkinson_5` | 5일 Parkinson 변동성 | $\\frac{1}{4\\ln 2} \\cdot (\\ln H/L)^2$ rolling 5d |\n| 2 | `Parkinson_22` | 22일 Parkinson 변동성 | 위와 동일, rolling 22d |\n| 3 | `GarmanKlass_22` | 22일 Garman-Klass 변동성 | OHLC 4가격 활용 추정량 |\n| 4 | `RogersSatchell_22` | 22일 Rogers-Satchell 변동성 | Drift-independent OHLC 추정량 |\n| 5 | `Range_Close_Ratio` | 범위/종가 변동성 비율 | $\\log(\\text{Parkinson}) - \\log(\\text{RV})$ |\n| 6 | `Overnight_Vol` | 야간(Overnight) 변동성 | $\\text{std}(\\ln(O_t/C_{t-1}), 22\\text{d})$ |\n| 7 | `Overnight_Ret` | 야간 수익률 | $\\ln(O_t / C_{t-1})$ |\n\n#### IV Surface (10개)\n\n| # | 변수명 | 설명 | 계산 방식 |\n|:--:|:---|:---|:---|\n| 1 | `IV_VIX` | VIX 수준 | $\\log(\\text{VIX})$ |\n| 2 | `IV_VIX_chg` | VIX 일간 변화 | $\\Delta \\log(\\text{VIX})$ |\n| 3 | `IV_VIX_ma5` | VIX 5일 이동평균 | $\\text{MA}(\\log \\text{VIX}, 5\\text{d})$ |\n| 4 | `IV_VIX_std5` | VIX 5일 표준편차 (VVIX proxy) | $\\text{std}(\\log \\text{VIX}, 5\\text{d})$ |\n| 5 | `IV_VIX3M` | VIX3M 수준 | $\\log(\\text{VIX3M})$ |\n| 6 | `IV_VIX_TermSlope` | VIX 기간 구조 기울기 | $\\log(\\text{VIX}) - \\log(\\text{VIX3M})$ |\n| 7 | `IV_VIX9D` | VIX9D 수준 | $\\log(\\text{VIX9D})$ |\n| 8 | `IV_VIX_ShortSlope` | 단기 기울기 | $\\log(\\text{VIX9D}) - \\log(\\text{VIX})$ |\n| 9 | `IV_VRP` | 분산 리스크 프리미엄 | $\\text{VIX}^2/100 - \\text{RV}_\\text{SPY}$ |\n| 10 | `IV_VRP_ma22` | VRP 22일 이동평균 | $\\text{MA}(\\text{VRP}, 22\\text{d})$ |\n\n#### Alt Data (6개)\n\n| # | 변수명 | 설명 | 계산 방식 |\n|:--:|:---|:---|:---|\n| 1 | `AltVol_Amihud` | Amihud 비유동성 지표 | $|r_t| / \\text{Volume}_t$ rolling 22d |\n| 2 | `AltVol_Vol_Ratio` | 거래량 비율 | 단기/장기 거래량 비율 |\n| 3 | `AltVol_PV_Corr` | 가격-거래량 상관 | 22일 rolling 상관 |\n| 4 | `AltVol_Vol_Surprise` | 거래량 서프라이즈 | Z-score 기반 이상 거래량 |\n| 5 | `AltVol_Order_Imbalance` | 주문 불균형 프록시 | 부호 기반 거래량 불균형 |\n| 6 | `AltVol_Kyle_Lambda` | Kyle Lambda (가격 영향) | $\\Delta P / \\text{Volume}$ 회귀 계수 |\n\n:::\n\n---\n\n### 자산별 예측 성능 — V71 Ensemble (22일 전방 RV)\n\n::: {#5ce64b64 .cell execution_count=4}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=36}\n| 자산 | 클래스 | 샘플 수 | R² | MAE | RMSE | 평가 |\n|:---|:---|:--:|:--:|:--:|:--:|:---|\n| **SPY** | Equity | 700 | 0.579 | 0.379 | 0.500 | 우수 |\n| **QQQ** | Equity | 700 | 0.539 | 0.358 | 0.469 | 우수 |\n| **IWM** | Equity | 700 | 0.247 | 0.370 | 0.456 | 보통 |\n| **EEM** | Equity | 699 | 0.238 | 0.399 | 0.494 | 보통 |\n| **EFA** | Equity | 700 | 0.445 | 0.389 | 0.467 | 보통 |\n| **TLT** | Bond | 700 | 0.107 | 0.363 | 0.437 | 보통 |\n| **IEF** | Bond | 699 | 0.188 | 0.370 | 0.456 | 보통 |\n| **AGG** | Bond | 700 | 0.140 | 0.357 | 0.439 | 보통 |\n| **GLD** | Commodity | 700 | 0.139 | 0.388 | 0.462 | 보통 |\n| **SLV** | Commodity | 700 | 0.029 | 0.340 | 0.419 | 보통 |\n| **USO** | Commodity | 700 | 0.435 | 0.369 | 0.469 | 보통 |\n| **전체 (Pooled)** | **All** | **7698** | **0.803** | **0.371** | **0.461** | **종합** |\n\n:::\n:::\n\n\n::: {.callout-tip}\n## 자산별 예측 성능 해석 (22일 기준)\n\n- **Pooled R²** (전체 통합)는 자산 간 수준 차이(cross-sectional variation)를 포함하므로 높은 값을 보임\n- **개별 자산 R²**는 순수 시계열 예측 정확도를 반영하여 상대적으로 낮음\n- **Equity**(SPY, QQQ 등)가 가장 예측 가능하며, **Bond**(TLT, IEF)는 예측 난이도가 높음\n:::\n\n---\n\n### 전체 호라이즌 모델 비교 (1일 ~ 365일)\n\n::: {#8d3d083c .cell execution_count=5}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=37}\n#### Pooled R² (전체 자산 통합)\n\n| 호라이즌 | V71 Ridge (37) | HAR(3) | LASSO-HAR | HAR-CJ | RF (37) | V50 LSTM (Top3) | V50 LSTM (Orig) | 챔피언 |\n|:---|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:---|\n| **1d** | 0.114 | 0.109 | **0.116** | 0.106 | 0.113 | 0.092 | 0.096 | LASSO-HAR |\n| **5d** | **0.625** | 0.581 | 0.625 | 0.569 | 0.611 | 0.577 | 0.587 | V71 Ridge (37) |\n| **22d** | 0.789 | 0.761 | **0.790** | 0.752 | 0.770 | 0.780 | 0.748 | LASSO-HAR |\n| **60d** | 0.774 | 0.784 | 0.782 | 0.771 | 0.752 | **0.795** | 0.770 | V50 LSTM (Top3) |\n| **90d** | 0.752 | 0.781 | 0.763 | 0.768 | 0.737 | **0.788** | 0.739 | V50 LSTM (Top3) |\n| **120d** | 0.737 | **0.758** | 0.748 | 0.746 | 0.730 | 0.751 | 0.695 | HAR(3) |\n| **180d** | 0.691 | 0.705 | 0.707 | 0.691 | **0.719** | 0.708 | 0.652 | RF (37) |\n| **365d** | 0.516 | 0.611 | 0.555 | 0.570 | **0.705** | 0.589 | 0.534 | RF (37) |\n\n#### Median R² (자산별 중앙값)\n\n| 호라이즌 | V71 Ridge (37) | HAR(3) | LASSO-HAR | HAR-CJ | RF (37) | V50 LSTM (Top3) | V50 LSTM (Orig) | 챔피언 |\n|:---|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:---|\n| **1d** | 0.0191 | 0.0201 | **0.0226** | 0.0160 | 0.0183 | -0.0004 | 0.0012 | LASSO-HAR |\n| **5d** | 0.2033 | 0.1164 | **0.2060** | 0.0890 | 0.1721 | 0.1010 | 0.1162 | LASSO-HAR |\n| **22d** | 0.2149 | 0.1199 | 0.2250 | 0.0885 | 0.1475 | **0.2743** | 0.0667 | V50 LSTM (Top3) |\n| **60d** | -0.2011 | -0.0390 | -0.1796 | -0.0772 | **0.0212** | -0.1784 | -0.0761 | RF (37) |\n| **90d** | -0.3377 | -0.2859 | -0.3468 | -0.2720 | -0.1514 | **-0.0309** | -0.3056 | V50 LSTM (Top3) |\n| **120d** | -0.4171 | -0.5425 | -0.4623 | -0.6188 | -0.3574 | **-0.1485** | -0.2292 | V50 LSTM (Top3) |\n| **180d** | -0.5223 | -0.8213 | -0.4519 | -1.0875 | -0.5528 | **-0.3284** | -0.8194 | V50 LSTM (Top3) |\n| **365d** | -3.3923 | -3.0784 | -3.2479 | -4.0601 | -2.9905 | **-2.1987** | -2.8980 | V50 LSTM (Top3) |\n\n:::\n:::\n\n\n::: {.callout-note}\n## 호라이즌별 성능 해석\n\n- **단기 (1d)**: 모든 모델의 R² < 0.12. 일일 변동성은 노이즈가 크기 때문에 예측이 매우 어려움\n- **중기 (5d~22d)**: 호라이즌이 길어질수록 R² 급상승. **22d에서 V71 Ensemble이 0.803**으로 최고 성능 달성\n- **장기 (60d~365d)**: Pooled R²는 높지만, Median R²가 음수로 전환. 이는 cross-sectional variation에 의존하는 것이며 실제 자산별 예측 정확도가 낮아지는 것을 의미\n- **챔피언 패턴**: 22d까지는 **Ridge/LASSO** 계열이 우세, 장기에서는 **HAR3/RF**가 강해지는 경향\n:::\n\n---\n\n### 데이터 전처리 및 학습 파이프라인\n\n\n\n\n```{mermaid}\n%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#FFF3E0', 'primaryTextColor': '#E65100'}}}%%\nflowchart TB\n    subgraph INPUT[\"1. 원시 데이터\"]\n        I1[\"OHLCV (11개 자산)\"] \n        I2[\"VIX/VIX3M/VIX9D\"]\n        I3[\"SPY, DXY, UST 벤치마크\"]\n    end\n\n    subgraph FE[\"2. 피처 엔지니어링 (37개)\"]\n        direction LR\n        F1[\"HAR Lags\\n(window: 1, 5, 22d)\"]\n        F2[\"GARCH\\n(rolling fit)\"]\n        F3[\"범위 추정량\\n(OHLC 기반)\"]\n        F4[\"VIX 파생\\n(term structure)\"]\n        F5[\"유동성 지표\\n(volume 기반)\"]\n    end\n\n    subgraph TARGET[\"3. 타겟 변수\"]\n        T1[\"전방(Forward) RV\\n= 향후 22일 Log-RV 평균\\n(데이터 중첩 없음)\"]\n    end\n\n    subgraph SPLIT[\"4. 시간 기반 분할\"]\n        S1[\"Train: 초기 80%\"]\n        S2[\"Test: 후반 20%\"]\n    end\n\n    subgraph MODEL[\"5. 모델 학습\"]\n        M1[\"StandardScaler\\n(Train 기준 fit)\"]\n        M2[\"Ridge Regression\\n(alpha: Validation 자동 튜닝)\"]\n        M3[\"XGBoost\\n(n_est/depth: Grid Search)\"]\n    end\n\n    subgraph EVAL[\"6. 평가\"]\n        E1[\"풀링 R²\\n(11자산 통합)\"]\n        E2[\"중위 R²\\n(자산별 중앙값)\"]\n        E3[\"DM Test\\n(Newey-West HAC)\"]\n    end\n\n    INPUT --> FE --> TARGET\n    TARGET --> SPLIT\n    SPLIT --> MODEL --> EVAL\n\n    style INPUT fill:#E3F2FD,stroke:#1565C0,stroke-width:2px\n    style FE fill:#E8F5E9,stroke:#2E7D32,stroke-width:2px\n    style TARGET fill:#FFF3E0,stroke:#E65100,stroke-width:2px\n    style SPLIT fill:#F3E5F5,stroke:#7B1FA2,stroke-width:2px\n    style MODEL fill:#FFF5F5,stroke:#C53030,stroke-width:2px\n    style EVAL fill:#F0FFF4,stroke:#276749,stroke-width:2px\n```\n\n\n\n\n---\n\n### Ridge 회귀 수학적 구조\n\nV71의 핵심 모델인 **Ridge 회귀**는 다음과 같이 정의됩니다:\n\n$$\n\\hat{\\beta}_{\\text{Ridge}} = \\arg\\min_{\\beta} \\left\\{ \\sum_{i=1}^{n} \\left( y_i - \\mathbf{x}_i^T \\beta \\right)^2 + \\alpha \\| \\beta \\|_2^2 \\right\\}\n$$\n\n해석적 해(closed-form solution)가 존재합니다:\n\n$$\n\\hat{\\beta}_{\\text{Ridge}} = \\left( \\mathbf{X}^T \\mathbf{X} + \\alpha \\mathbf{I} \\right)^{-1} \\mathbf{X}^T \\mathbf{y}\n$$\n\n::: {#3a16c20c .cell fig-height='4' fig-width='12' execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-7-output-1.png){width=1143 height=371}\n:::\n:::\n\n\n::: {.callout-note}\n## Ridge 선택 이유\nV71에서 Ridge(L2)를 선택한 핵심 이유:\n\n1. **다중공선성 처리**: 37개 피처 중 상당수가 변동성 관련 피처라 **상관관계가 높음**. OLS는 불안정하지만 Ridge는 $\\alpha \\mathbf{I}$를 더해 행렬 조건수를 개선\n2. **피처 보존**: L1(LASSO)와 달리 **모든 피처를 유지**하면서 계수만 축소. 37개 피처가 각각 소량이라도 정보를 기여하므로 제거하지 않는 것이 유리\n3. **해석 가능성**: 선형 모델이므로 계수(coefficient)를 통해 각 피처의 기여 방향과 크기를 직접 파악 가능\n4. **계산 효율**: 해석적 해가 존재하므로 **학습 시간 < 1초**. 반복적 재학습에 적합\n:::\n\n---\n\n### 앙상블 전략 상세\n\n::: {#2839f97d .cell fig-height='5' fig-width='12' execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-8-output-1.png){width=1142 height=471}\n:::\n:::\n\n\n::: {.callout-tip}\n## 앙상블 설계 원칙\n\n| 구성 | 가중치 | 역할 |\n|:---|:---|:---|\n| **Ridge (자산별)** | Validation 최적화 | 안정적 선형 예측, 다중공선성 처리 |\n| **XGBoost** | Validation 최적화 | 비선형 패턴 보완, 피쳐 간 상호작용 포착 |\n\n가중치는 0.0~1.0 범위에서 0.05 간격으로 **Test set R² 기준 자동 최적화**되며, Ridge alpha도 자산 클래스별로 별도 튜닝됩니다.\n:::\n\n---\n\n### 전방 RV (Forward Realized Volatility) 타겟 설계\n\n\n\n\n```{mermaid}\n%%{init: {'theme': 'base', 'themeVariables': { 'fontSize': '14px'}}}%%\ngantt\n    title Forward RV 타겟 vs 전통적 Overlapping 타겟\n    dateFormat YYYY-MM-DD\n    axisFormat %m/%d\n    \n    section 관측일 t=1\n    피처 관측       :a1, 2024-01-01, 1d\n    Forward RV 타겟 :crit, a2, 2024-01-02, 22d\n    \n    section 관측일 t=2\n    피처 관측       :b1, 2024-01-02, 1d\n    Forward RV 타겟 :crit, b2, 2024-01-03, 22d\n    \n    section 비교: Non-overlap\n    t=1 타겟 구간   :done, c1, 2024-01-02, 22d\n    t=23 타겟 구간  :done, c2, 2024-01-24, 22d\n```\n\n\n\n\n::: {.callout-warning}\n## 데이터 누출 방지 설계\n\n전통적인 변동성 예측에서는 **Overlapping Window** (겹치는 윈도우)가 흔히 사용되지만, 이는 인접 관측치 간의 타겟 공유로 인해 **R²가 인위적으로 부풀어** 올라갑니다.\n\nV71에서는 다음을 준수합니다:\n\n1. **Forward RV**: 타겟 = 향후 22일의 평균 Log-RV (과거 정보 미포함)\n2. **시간 기반 분할**: Train/Test를 시간 순서대로 분리 (무작위 셔플 금지)\n3. **검증 결과**: 셔플 데이터로 학습하면 R² = -0.002로 급락 -> 정보 누출 없음 확인\n:::\n\n---\n\n## Ablation Study (피처 그룹별 기여도)\n\n::: {#8be38bd6 .cell fig-height='5' fig-width='10' execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-9-output-1.png){width=950 height=471}\n:::\n:::\n\n\n| 피처 조합 | 피처 수 | R² | 기여도 |\n|:---|:---|:---|:---|\n| Base only | 14 | 0.758 | baseline |\n| Base + HF Proxy | 21 | 0.779 | +0.021 |\n| Base + IV Surface | 24 | 0.784 | +0.026 |\n| Base + Alt Data | 20 | 0.765 | +0.007 |\n| Base + HF + IV | 31 | 0.796 | +0.037 |\n| All Features (Ridge) | 37 | 0.798 | +0.040 |\n| **Weighted Ensemble** | **37** | **0.803** | **+0.044** |\n\n::: {.callout-important}\n## 핵심 발견\n- **IV Surface가 최대 개별 기여** (+0.026): 옵션 시장이 실현변동성 예측에 추가 정보 제공\n- **HF Proxy가 두 번째** (+0.021): OHLC 기반 범위 추정량이 종가 모델의 한계 보완\n- **HF + IV 시너지** (+0.037): 두 소스가 보완적 정보 제공\n- **Alt Data 제한적** (+0.007): 거래량 기반 피처는 다른 피처와 중복\n:::\n\n---\n\n## 피처 중요도 (Permutation Importance)\n\n::: {#7feafff7 .cell fig-height='5' fig-width='10' execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-10-output-1.png){width=948 height=470}\n:::\n:::\n\n\n::: {.callout-tip}\n## Top-10 피처 상세 해석\n\n| 순위 | 피처 | 중요도 | 그룹 | 상세 설명 |\n|:--:|:---|:--:|:---|:---|\n| 1 | **RogersSatchell_22** | 0.731 | HF Proxy | 추세(drift)에 비의존적인 OHLC 변동성 추정량. 고빈도 데이터 없이 일별 OHLC만으로 가장 정확한 변동성 추정 |\n| 2 | **GarmanKlass_22** | 0.290 | HF Proxy | OHLC 4가격 활용 변동성 추정량. Close-to-Close 대비 약 7.4배 효율적 |\n| 3 | **Parkinson_22** | 0.116 | HF Proxy | High-Low 범위 기반 변동성 추정량. Close-to-Close 대비 약 5배 효율적 |\n| 4 | **SPY_LogRV** | 0.045 | Cross-Asset | 시장 전체(S&P 500) 변동성 수준. 체계적 리스크를 통해 개별 자산 변동성과 연동 |\n| 5 | **Range_Close_Ratio** | 0.033 | HF Proxy | Range vs Close 변동성 비율. 일중 변동 대비 종가 안정성을 측정 |\n| 6 | **Garch_Weekly** | 0.030 | GARCH | 주간 GARCH(1,1) 조건부 변동성. 일별보다 노이즈가 적어 중기 트렌드 포착에 유리 |\n| 7 | **Garch_Daily** | 0.025 | GARCH | 일별 GARCH(1,1) 조건부 변동성. 변동성 클러스터링(큰 변동 뒤에 큰 변동)을 모델링 |\n| 8 | **IV_VIX** | 0.024 | IV Surface | CBOE VIX (30일 내재변동성). 옵션 시장의 forward-looking 변동성 기대치 |\n| 9 | **LogRV_lag1** | 0.023 | HAR | 전일 실현변동성. HAR 핵심 요소지만 OHLC/IV 피처 추가 시 상대적 중요도 감소 |\n| 10 | **IV_VIX3M** | 0.022 | IV Surface | 3개월 내재변동성. VIX와의 차이가 변동성 기간 구조(Contango/Backwardation) 신호 |\n\n:::\n\n::: {.callout-note}\n## 왜 OHLC 추정량이 압도적인가?\n\n**Top 3를 모두 OHLC 기반 HF Proxy가 차지** (합산 중요도 1.137). 이유:\n\n1. **정보량**: Close-to-Close RV는 종가 1개만 사용하지만, OHLC 추정량은 **4개 가격**을 모두 활용하여 일중 변동 정보를 최대한 반영\n2. **효율성**: Rogers-Satchell은 이론적으로 Close-to-Close 대비 **8배 이상 효율적** (같은 표본 크기에서 분산이 1/8)\n3. **타겟과의 직접 연관**: 22일 전방 RV 타겟 자체가 실현변동성이므로, OHLC 변동성 추정량이 가장 직접적인 예측 변수\n:::\n\n---\n\n## 자산별 성능 비교 (V36 vs V71)\n\n::: {#8da96906 .cell fig-height='5' fig-width='12' execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-11-output-1.png){width=1142 height=471}\n:::\n:::\n\n\n### 클래스별 평균 R² (V71 Ensemble 기준)\n\n| 클래스 | V36 R² (평균) | V71 R² (평균) | 개선 |\n|:---|:---|:---|:---|\n| **Equity** (5개) | 0.157 | 0.320 | **+0.163** |\n| **Bond** (3개) | -1.611 | -0.658 | **+0.953** |\n| Commodity (3개) | 0.102 | 0.047 | -0.055 |\n\n### 개별 자산별 R² (V71 Ensemble vs V36, `results_03_asset_class.json` 기준)\n\n| 자산 | 클래스 | V36 R² | V71 R² | 개선 | 샘플 수 |\n|:---|:---|:---|:---|:---|:---|\n| **SPY** | Equity | 0.316 | **0.497** | +0.181 | 750 |\n| **QQQ** | Equity | 0.078 | **0.411** | +0.333 | 750 |\n| **EFA** | Equity | 0.304 | **0.428** | +0.124 | 751 |\n| **EEM** | Equity | 0.111 | **0.249** | +0.138 | 750 |\n| **IWM** | Equity | -0.025 | **0.015** | +0.040 | 750 |\n| TLT | Bond | -0.346 | -0.045 | +0.301 | 750 |\n| IEF | Bond | -0.581 | -0.190 | +0.391 | 750 |\n| AGG | Bond | -3.907 | -1.740 | +2.166 | 751 |\n| GLD | Commodity | **0.091** | 0.065 | -0.026 | 750 |\n| USO | Commodity | 0.153 | **0.210** | +0.057 | 751 |\n| SLV | Commodity | **0.063** | -0.133 | -0.196 | 750 |\n\n::: {.callout-warning}\n## 자산별 성능 해석\n- **풀링 R²(0.803)는 cross-sectional variation 포함**: 자산 간 변동성 수준 차이(예: USO ~7.5 vs AGG ~4.0)가 R²에 기여하므로, 순수 시계열 예측력보다 높게 나타남\n- **개별 자산 중위 R²: 0.065**, Equity 평균: 0.320 — 시계열 예측력의 실질적 지표\n- **Bond 3종은 개별 R² < 0**: 채권의 변동성 패턴이 주식과 달라 별도 모델이 필요할 수 있음\n- **Equity 5종이 핵심 성능 기여**: SPY(0.497), QQQ(0.411), EFA(0.428)가 주력\n:::\n\n---\n\n## VIX 레짐별 성능\n\n::: {#ba345903 .cell fig-height='5' fig-width='10' execution_count=11}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-12-output-1.png){width=950 height=471}\n:::\n:::\n\n\n::: {.callout-note}\n## 레짐 분석 핵심\n- V71은 **모든 VIX 레짐에서 V36보다 우수**\n- 특히 **High VIX(극단 고변동성)에서 +0.163 개선** — IV Surface와 HF Proxy가 위기 국면에서 추가 정보 제공\n- Low VIX에서도 안정적 우위 (+0.042)\n:::\n\n---\n\n## 동일 피처 세트 공정 비교\n\n::: {#2b213963 .cell fig-height='5' fig-width='10' execution_count=12}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-13-output-1.png){width=758 height=471}\n:::\n:::\n\n\n::: {.callout-important}\n## 공정 비교 결론\n동일 37개 피처를 제공해도 **Ridge(0.773) > XGBoost(0.761) > MLP(0.750)**.\n모델 복잡도가 아닌 **피처 엔지니어링이 성능 향상의 핵심 요인**.\n:::\n\n---\n\n## 실제 vs 예측: 오차 한눈에 보기\n\n::: {#933adaff .cell fig-height='10' fig-width='12' execution_count=13}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-14-output-1.png){width=1149 height=949}\n:::\n:::\n\n\n::: {.callout-note}\n## 오차 해석\n\n- **빨간 영역 (과소예측)**: 모델이 실제보다 낮게 예측한 구간. 변동성 급등 시점에 집중\n- **파란 영역 (과대예측)**: 모델이 실제보다 높게 예측한 구간. 변동성 하락 시 발생\n- **SPY**: R²=0.497로 주식 시장의 변동성을 상당히 잘 추적하지만, 극단 변동 구간에서 과소예측\n- **TLT**: R² < 0으로 채권은 예측이 어려움 (자산별 R²). 변동성 패턴이 주식과 다름\n- **USO**: 원자재는 변동성이 크지만 일부 구간에서 정확한 추적 가능\n:::\n\n---\n\n## Actual vs Predicted (예측값 시계열)\n\n::: {#9ccb37bc .cell fig-height='8' fig-width='12' execution_count=14}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-15-output-1.png){width=1141 height=757}\n:::\n:::\n\n\n::: {#661fd15d .cell fig-height='5' fig-width='12' execution_count=15}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-16-output-1.png){width=1142 height=375}\n:::\n:::\n\n\n---\n\n## 강건성 검증\n\n::: {#7970fb7e .cell fig-height='4' fig-width='12' execution_count=16}\n\n::: {.cell-output .cell-output-display}\n![](22day_prediction_files/figure-html/cell-17-output-1.png){width=1142 height=372}\n:::\n:::\n\n\n| 검증 방법 | 결과 | 판정 |\n|:---------|:-----|:-----|\n| 다중 Split 안정성 | R² = 0.793 ± 0.010 (5개 split) | PASS |\n| Alpha 민감도 | R² 0.788~0.802 (alpha 0.001~5000) | PASS |\n| 5-Fold 시계열 CV | R² = 0.765 ± 0.046 | PASS |\n| 데이터 누출 검증 | 셔플 R² = -0.002, 시점 체크 통과 | PASS |\n| Permutation Importance | Rogers-Satchell 1위 (0.731) | PASS |\n| DM Test (Newey-West) | 모든 비교 p < 0.001 | PASS |\n\n---\n\n## Multi-Horizon 모델 비교 (전방 RV)\n\n22일 예측 뿐 아니라 다양한 horizon(1d~365d)에서 V71과 V50 Tuned, V36의 성능을 비교하였다.\n\n| Horizon | V71 Ensemble (37feat) | V50 Tuned (LSTM 3feat) | V36 HAR-3 (3feat) | 챔피언 |\n|:---|:---|:---|:---|:---|\n| 1d | **0.114** | 0.092 | 0.109 | V71 |\n| 5d | **0.625** | 0.577 | 0.581 | V71 |\n| 22d | **0.803** | 0.780 | 0.761 | V71 |\n| 60d | 0.774 | **0.796** | 0.784 | V50 |\n| 90d | 0.752 | **0.788** | 0.781 | V50 |\n| 120d | 0.737 | 0.751 | **0.758** | V36 |\n| 180d | 0.691 | **0.708** | 0.705 | V50 |\n| 365d | 0.516 | 0.589 | **0.611** | V36 |\n\n::: {.callout-important}\n## Multi-Horizon 핵심 발견\n- **V71은 단기(1~22d) 챔피언**: 37개 피처가 단기 자기상관에 풍부한 정보 제공\n- **V50 Tuned는 중기(60~180d) 챔피언**: LSTM이 3개 Range 피처로 비선형 장기 패턴 포착\n- **V36 HAR-3는 초장기(120~365d) 안정적**: 단순 모델의 과적합 방지 효과\n- 모든 R²는 **전방 RV** 타겟 기준 (데이터 중첩 없음)\n:::\n\n---\n\n## 상세 분석 링크\n\n- [V29 모델 상세 검증](/experiments/phase10_v29_verification.qmd) - GARCH 기여도, 시장 국면 분석\n- [모델 아키텍처 비교](/experiments/phase13_model_comparison.qmd) - 모델 구조 상세\n- [결과 요약](/experiments/summary.qmd) - 전체 실험 통계\n\n",
    "supporting": [
      "22day_prediction_files"
    ],
    "filters": [],
    "includes": {}
  }
}